`include "tester.v"

// Testbench Code Goes here
module Controlador_tb;

  wire clk, reset;
  wire TARJETA_RECIBIDA, TIPO_TRANS, DIGITO_STB, MONTO_STB;
  wire [3:0] DIGITO;
  wire [15:0] PIN_CORRECTO;
  wire [31:0] MONTO;
  wire [63:0] BALANCE_INICIAL;

  wire BALANCE_STB, ENTREGA_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES;
  wire [63:0] BALANCE_ACTUALIZADO;

  initial begin
    $dumpfile("resultados.vcd");
    $dumpvars(-1, U0);
    $monitor("TARJETA_RECIBIDA=%b, TIPO_TRANS=%b, DIGITO_STB=%b, MONTO_STB=%b, DIGITO=%h, PIN_CORRECTO=%h, MONTO=%h, BALANCE_INICIAL=%h, BALANCE_STB=%b, ENTREGA_DINERO=%b, PIN_INCORRECTO=%b, ADVERTENCIA=%b, BLOQUEO=%b, FONDOS_INSUFICIENTES=%b, BALANCE_ACTUALIZADO=%h",
      TARJETA_RECIBIDA, TIPO_TRANS, DIGITO_STB, MONTO_STB, DIGITO, PIN_CORRECTO, MONTO, BALANCE_INICIAL,
      BALANCE_STB, ENTREGA_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES, BALANCE_ACTUALIZADO);
  end

  Controlador U0 (
    .clk(clk),
    .reset(reset),
    .TARJETA_RECIBIDA(TARJETA_RECIBIDA),
    .TIPO_TRANS(TIPO_TRANS),
    .DIGITO_STB(DIGITO_STB),
    .MONTO_STB(MONTO_STB),
    .DIGITO(DIGITO),
    .PIN_CORRECTO(PIN_CORRECTO),
    .MONTO(MONTO),
    .BALANCE_INICIAL(BALANCE_INICIAL),
    .BALANCE_STB(BALANCE_STB),
    .ENTREGA_DINERO(ENTREGA_DINERO),
    .PIN_INCORRECTO(PIN_INCORRECTO),
    .ADVERTENCIA(ADVERTENCIA),
    .BLOQUEO(BLOQUEO),
    .FONDOS_INSUFICIENTES(FONDOS_INSUFICIENTES),
    .BALANCE_ACTUALIZADO(BALANCE_ACTUALIZADO)
  );

  probador P0 (
    .clk(clk),
    .reset(reset),
    .TARJETA_RECIBIDA(TARJETA_RECIBIDA),
    .TIPO_TRANS(TIPO_TRANS),
    .DIGITO_STB(DIGITO_STB),
    .MONTO_STB(MONTO_STB),
    .DIGITO(DIGITO),
    .PIN_CORRECTO(PIN_CORRECTO),
    .MONTO(MONTO),
    .BALANCE_INICIAL(BALANCE_INICIAL),
    .BALANCE_STB(BALANCE_STB),
    .ENTREGA_DINERO(ENTREGA_DINERO),
    .PIN_INCORRECTO(PIN_INCORRECTO),
    .ADVERTENCIA(ADVERTENCIA),
    .BLOQUEO(BLOQUEO),
    .FONDOS_INSUFICIENTES(FONDOS_INSUFICIENTES),
    .BALANCE_ACTUALIZADO(BALANCE_ACTUALIZADO)
  );

endmodule



